Implement basic router
mishka-group/mishka-cms-android-flutter pull request #3
Opened 2022-01-06 18:41 UTC by husen-hn

this is an early version of the application router.

- MishkaRouter (the top layer of the router, including settings for navigating forward and backward and ...)
- Routes (include all routes and their proprietary names and set specific blocs for each page)
- RouteName (all route names for easy access)

2022-01-06 21:37 UTC, shahryarjb requested changes

2022-01-06 21:37 UTC, shahryarjb commented on lib/apps/helper/mishka_router.dart
> +class MishkaRouter {
Please change this file name, `MishkaRouter` is no a sup-projects in elixir version

You should have a file that it's name is `RouterSchema`. In this file, developers should be able to add and delete item of router list in this class.

## Example:

```swift
struct RouterSchema: Identifiable {
    var id = UUID()
    var title: String
    var icon: String
    var nav: SelectNavigation
}

var routers = [
    RouterSchema(title: "Home", icon: "house", nav: .home),
    RouterSchema(title: "Blogs", icon: "square.3.stack.3d", nav: .blogs),
    RouterSchema(title: "Login", icon: "lock", nav: .login)
]

enum SelectNavigation {
    case home
    case blogs
    case login
}
```

If you see this file, I add my Enum in end of this Class instead of creating a new file then move your enum codes into it

2022-01-06 21:37 UTC, shahryarjb commented on lib/apps/enums/route_name.dart
> +enum RouteName { signIn, signUp, mishkaBlog, mishkaArticle }
I talked about it in `MishkaRouter` part, move your code into the class concerned and delete this file, it is unnecessary.

And please don't create `Enums` or etc as a plural name, just use a singular name, and don't create a new folder like Enum out of the helper file

2022-01-06 21:37 UTC, shahryarjb commented on lib/routes.dart
> +      case '/':
This part of your code is duplicate, make clear please and convert it as a new function and the new file I suggested you I mean `RouterSchema` can help you because router icon and name, etc are saved in this class.

```dart
return MaterialPageRoute(builder: (_) {
  return const SignIn();
});
```

2022-01-06 22:20 UTC, mojtaba-naseri commented
Please do not put any files out of the `MishkaCms` app structure.

Thanks for your collaboration.
💚 💙 💜 💛 ❤️

2022-01-07 07:12 UTC, iArazar commented
Please write some tests for UI and functions; after this, the code would be clear to understand even for none-dart-developers.

2022-01-10 21:30 UTC, shahryarjb approved these changes

2022-01-12 16:54 UTC, merged

2022-01-14 08:39 UTC, shahryarjb commented
💚 💙 💜 💛 ❤️
Merged